#!/usr/bin/env php

<?php
echo "Running npm run lint...";
exec('npm run lint', $output, $returnCode);
if ($returnCode !== 0) {
    echo implode("\n", $output);
    echo "\nERROR: git push aborted because the lint failed. ";
    exit(1);
}

echo "\nRunning npm run test...";
exec('npm run test', $output, $returnCode);
if ($returnCode !== 0) {
    echo implode("\n", $output);
    echo "\nERROR: git push aborted because the tests failed. ";
    exit(1);
}

echo "\n";
exit(0);
